<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		
		<title>CVE-2020-5390 - Vulnerability Data</title>
		
		<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-175514417-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-175514417-4');
</script>

	</head>
<body>
	<div class="container">
	

  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href="https://www.vulnerabilitydata.com" class="breadcrumb">Vulnerability Data</a>
        <a href="/2020" class="breadcrumb">2020</a>
        <a href="#" class="breadcrumb">CVE-2020-5390</a>
      </div>
    </div>
  </nav>

<h2>Vulnerability Data</h2>
<h1>CVE-2020-5390</h1>
<p>PySAML2 before 5.0.0 does not check that the signature in a SAML document is enveloped and thus signature wrapping is effective, i.e., it is affected by XML Signature Wrapping (XSW). The signature information and the node/object that is signed can be in different places and thus the signature verification will succeed, but the wrong data will be used. This specifically affects the verification of assertion that have been signed.</p>

<dl>
	<dt>Published</dt>
	<dd>2020-01-13</dd>

	<dt>Modified</dt>
	<dd>2020-02-26</dd>
</dl>

<h3>References</h3>
<ul>
	<li><a href="https://github.com/IdentityPython/pysaml2/commit/5e9d5acbcd8ae45c4e736ac521fd2df5b1c62e25">CONFIRM:https://github.com/IdentityPython/pysaml2/commit/5e9d5acbcd8ae45c4e736ac521fd2df5b1c62e25</a></li>
<li><a href="https://github.com/IdentityPython/pysaml2/commit/f27c7e7a7010f83380566a219fd6a290a00f2b6e">CONFIRM:https://github.com/IdentityPython/pysaml2/commit/f27c7e7a7010f83380566a219fd6a290a00f2b6e</a></li>
<li><a href="https://github.com/IdentityPython/pysaml2/releases">CONFIRM:https://github.com/IdentityPython/pysaml2/releases</a></li>
<li><a href="https://github.com/IdentityPython/pysaml2/releases/tag/v5.0.0">CONFIRM:https://github.com/IdentityPython/pysaml2/releases/tag/v5.0.0</a></li>
<li><a href="https://www.debian.org/security/2020/dsa-4630">DEBIAN:DSA-4630</a></li>
<li><a href="https://pypi.org/project/pysaml2/5.0.0/">MISC:https://pypi.org/project/pysaml2/5.0.0/</a></li>
<li><a href="https://lists.debian.org/debian-lts-announce/2020/02/msg00025.html">MLIST:[debian-lts-announce] 20200226 [SECURITY] [DLA 2119-1] python-pysaml2 security update</a></li>
<li><a href="https://usn.ubuntu.com/4245-1/">UBUNTU:USN-4245-1</a></li>
</ul>

<footer>
	<p><a href="https://reconmap.org">Track security vulnerabilities</a> with <strong>Reconmap</strong>.</p>
</footer>


	</div>
</body>
</html>