<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		
		<title>CVE-2020-8492 - Vulnerability Data</title>
		
		<link rel="shortcut icon" type="image/png" href="/favicon.ico" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
		  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XL44S2GJJ7"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XL44S2GJJ7');
</script>
	</head>
<body>
	<div class="container">
	

  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <a href="https://www.vulnerabilitydata.com" class="breadcrumb">Vulnerability Data</a>
        <a href="/2020" class="breadcrumb">2020</a>
        <a href="#" class="breadcrumb">CVE-2020-8492</a>
      </div>
    </div>
  </nav>

<h2>Vulnerability Data</h2>
<h1>CVE-2020-8492</h1>
<p>Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.</p>

<dl>
	<dt>Published</dt>
	<dd>2020-01-30</dd>

	<dt>Modified</dt>
	<dd>2021-08-16</dd>
</dl>

<h3>References</h3>
<ul>
	<li><a href="https://security.netapp.com/advisory/ntap-20200221-0001/">CONFIRM:https://security.netapp.com/advisory/ntap-20200221-0001/</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7WOKDEXLYW5UQ4S7PA7E37IITOC7C56J/">FEDORA:FEDORA-2020-6a88dad4a0</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UESGYI5XDAHJBATEZN3MHNDUBDH47AS6/">FEDORA:FEDORA-2020-8bdd3fd7a4</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/APGWEMYZIY5VHLCSZ3HD67PA5Z2UQFGH/">FEDORA:FEDORA-2020-98e0f0f11b</a></li>
<li><a href="https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A5NSAX4SC3V64PGZUPH7PRDLSON34Q5A/">FEDORA:FEDORA-2020-ea5bdbcc90</a></li>
<li><a href="https://security.gentoo.org/glsa/202005-09">GENTOO:GLSA-202005-09</a></li>
<li><a href="https://bugs.python.org/issue39503">MISC:https://bugs.python.org/issue39503</a></li>
<li><a href="https://github.com/python/cpython/pull/18284">MISC:https://github.com/python/cpython/pull/18284</a></li>
<li><a href="https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html">MISC:https://python-security.readthedocs.io/vuln/urllib-basic-auth-regex.html</a></li>
<li><a href="https://lists.apache.org/thread.html/rdb31a608dd6758c6093fd645aea3fbf022dd25b37109b6aaea5bc0b5@%3Ccommits.cassandra.apache.org%3E">MLIST:[cassandra-commits] 20210816 [jira] [Created] (CASSANDRA-16857) Security vulnerability CVE-2020-8492</a></li>
<li><a href="https://lists.apache.org/thread.html/rfec113c733162b39633fd86a2d0f34bf42ac35f711b3ec1835c774da@%3Ccommits.cassandra.apache.org%3E">MLIST:[cassandra-commits] 20210816 [jira] [Updated] (CASSANDRA-16857) Security vulnerability CVE-2020-8492</a></li>
<li><a href="https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html">MLIST:[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update</a></li>
<li><a href="http://lists.opensuse.org/opensuse-security-announce/2020-03/msg00003.html">SUSE:openSUSE-SU-2020:0274</a></li>
<li><a href="https://usn.ubuntu.com/4333-1/">UBUNTU:USN-4333-1</a></li>
<li><a href="https://usn.ubuntu.com/4333-2/">UBUNTU:USN-4333-2</a></li>
</ul>

<footer>
	<p><a href="https://reconmap.org">Track security vulnerabilities</a> with <strong>Reconmap</strong>.</p>
</footer>


	</div>
</body>
</html>